### ISSUE TITLE
Support for arguments

### ISSUE THREAD

**Issue by melinath** [melinath/django-graph-api#32]
Add support for GraphQL [arguments](http://graphql.org/learn/queries/#arguments). For now, these should simply be accessible as arguments to get_FOO methods on schema objects.

This also includes making sure that inputs are properly coerced according to the [GraphQL scalars spec](http://facebook.github.io/graphql/October2016/#sec-Scalars).

**Comment by ariannedee** [comment]
Fixed in #49
