### ISSUE TITLE
Operation validation

### ISSUE THREAD

**Issue by melinath** [melinath/django-graph-api#50]
As a first step to validation, we should implement operation validation as a simple base case, including implementing the basic behavior of validation.

## Requirements

For full requirements, see the [validation specification](http://facebook.github.io/graphql/October2016/#sec-Validation), including section 5.1 (Operations). The following additional requirements apply for this project:

1. Validation must run before execution, and should run as immediately before execution as possible.
2. Invalid queries must not be executed.
3. If a query is invalid, an exception must be raised. This may be a custom error class.

## Exclusions

- For now, we should not cache the results of validation. This ticket has the goal of being finished as quickly as possible so that other validation tickets can be worked on.

**Comment by melinath** [comment]
See #48 for some examples of recursion that are currently unhandled. These will probably be handled correctly by implementing validation as described, but just in case.

**Comment by Allan-Nava** [comment]
Is still live this project

**Comment by melinath** [comment]
Yep!

**Comment by Allan-Nava** [comment]
Is possibile invite friends or share With this plugin?

**Comment by melinath** [comment]
@Allan-Nava I'm not quite sure how to answer your question, but it seems off topic for this thread. If you want to discuss the project, please join our [slack channel](https://slack-djangographapi.now.sh/).

**Comment by Allan-Nava** [comment]
@melinath Ok thanks ! I join in your slack channel
