### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by melinath** [melinath/django-graph-api#55]
If an exception is raised during validation (#50) or execution of a query, that error needs to be caught and returned to the user in the response.

## Requirements

For basic requirements, see the [GraphQL spec section 7.2.2](http://facebook.github.io/graphql/October2016/#sec-Errors). Additional requirements for this project:

1. Handle arbitrary python exceptions.
2. Optionally, define and custom errors that can be raised during validation or execution, if that would be useful for providing additional information.

## Exclusions

- We do not need to associate any errors with particular points unless that information is almost harder to not include :-)

**Comment by caffodian** [comment]
other issues I've run into:

- [ ] probably need to throw & catch a more useful error from schema.execute
- [ ] JSON parsing error text changes based on Python version
