### ISSUE TITLE
Non-null fields

### ISSUE THREAD

**Issue by melinath** [melinath/django-graph-api#57]
GraphQL has a concept of Non-Null Types. This ticket covers fields, and not arguments.

## Requirements

The parts of the [Non-Null type documentation](http://facebook.github.io/graphql/October2016/#sec-Types.Non-Null) related to fields are covered by this ticket.

Non-Null needs to be represented as a "wrapping type" in relation to the API (for example when coercing a field value or [introspecting the API](http://facebook.github.io/graphql/October2016/#sec-Type-Kinds.Non-Null)), but would probably be better represented as `null=False` on field definitions to match Django conventions.

## Exclusions

As validation does not yet exist in django-graph-api, [validation of non-null arguments](http://facebook.github.io/graphql/October2016/#sec-Required-Non-Null-Arguments) should not happen as part of this ticket.

**Comment by fugu13** [comment]
I'm going to take an attempt at this one here at PyCascades

**Comment by fugu13** [comment]
Pausing on this, if anyone wants to take it on. This requires either major restructuring or meta class manipulation.
