### ISSUE TITLE
Add management command for loading test data

### ISSUE THREAD

**Issue by melinath** [melinath/django-graph-api#64]
Right now, the [documentation for running the project](http://django-graph-api.readthedocs.io/en/0.2.0/start_developing.html#run-the-test-project) contains the following lines:

```
# Add some data
# django_graph_api/tests/conftest.py has some code you can copy and paste
```

This is not conducive to people getting started easily with the project. It would be great to supply a [management command](https://docs.djangoproject.com/en/2.0/howto/custom-management-commands/) as part of the test app which loads default data for people.

**Comment by wooken** [comment]
Hello. I am currently looking at this issue. =)
