### ISSUE TITLE
Add testing of multiple django versions

### ISSUE THREAD

**Issue by melinath** [melinath/django-graph-api#65]
Currently, our travis.yml file includes testing for python 2.7, 3.5, and 3.6, but only tests for django 1.11. It would be great if we could increase the range of django versions we test so that we can say explicitly which versions we support.

**Comment by swimmingbean** [comment]
i'm claiming this one

**Comment by ariannedee** [comment]
Now supports 1.8 and 2.0. Thanks @swimmingbean!
