### ISSUE TITLE
Populate the API reference page

### ISSUE THREAD

**Issue by nhuntwalker** [melinath/django-graph-api#86]
The Schema, Types, and Views headings aren't actually populated with any information about the API. That needs to change

**Comment by swimmingbean** [comment]
@nhuntwalker this is apparently some kind of display issue. I believe this info was rendering ok earlier

**Comment by swimmingbean** [comment]
claiming this

**Comment by swimmingbean** [comment]
@melinath is fixing this by changing some settings in readthedocs

**Comment by ariannedee** [comment]
Fixed by enabling the option: "Install your project inside a virtualenv using setup.py install"
